### ISSUE TITLE
Allow scarb new to accept `-` in name

### ISSUE THREAD

**Issue by ClementWalter** [software-mansion/scarb#1162] opened 2024-02-24 15:02 UTC
### Problem

`scarb new` will raise when using a `-` in the `new` command

```
error: invalid value 'my-cairo-project' for '--name <NAME>': invalid character `-` in package name: `my-cairo-project`, characters must be ASCII lowercase letters, ASCII numbers or underscore
```

it's however common case to have folder names with `-` but package name actually with `_` instead.

Furthermore, doing `mkdir my-cairo-project && cd my-cairo-project && scarb init my_cairo_project` is legit.

### Proposed Solution

Just accept the `-` and replace in the package name with `_`

**Comment by milancermak** [comment] 2024-02-26 15:53
Dup of #278 😇

**Comment by maciektr** [comment] 2024-02-26 16:49
Hi!
This is a intentional decision. 
Closing as duplicate of #278

**Closed by maciektr** 2024-02-26 16:49 UTC
